---
collections:
  - name: ansible.windows
    version: ">=2.5.0"
  - name: community.windows
    version: ">=2.3.0"
  - name: community.general
    version: ">=9.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.docker
    version: ">=3.10.0"
